### ISSUE TITLE
Unable to pause activity: Receiver not registered

### ISSUE THREAD

**Issue by AlvaroBrey** [cotechde/hwsecurity#4]
Hello, we're seeing a bun

**Comment by z4yx** [comment]
Got the same problem when using TermBot with OpenPGP hardware key.
```
01-18 20:51:36.803 20895 20895 E AndroidRuntime: FATAL EXCEPTION: main
01-18 20:51:36.803 20895 20895 E AndroidRuntime: Process: org.sufficientlysecure.termbot, PID: 20895
01-18 20:51:36.803 20895 20895 E AndroidRuntime: java.lang.RuntimeException: Unable to pause activity {org.sufficientlysecure.termbot/org.connectbot.ConsoleActivity}: java.lang.IllegalArgumentException: Receiver not registered: de.cotech.hw.internal.transport.usb.UsbConnectionDispatcher$1@a1b05b6
01-18 20:51:36.803 20895 20895 E AndroidRuntime:        at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:4908)
01-18 20:51:36.803 20895 20895 E AndroidRuntime:        at android.app.ActivityThread.performPauseActivity(ActivityThread.java:4854)
01-18 20:51:36.803 20895 20895 E AndroidRuntime:        at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:4802)
01-18 20:51:36.803 20895 20895 E AndroidRuntime:        at android.app.servertransaction.PauseActivityItem.execute(PauseActivityItem.java:46)
01-18 20:51:36.803 20895 20895 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
01-18 20:51:36.803 20895 20895 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
01-18 20:51:36.803 20895 20895 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2173)
01-18 20:51:36.803 20895 20895 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
01-18 20:51:36.803 20895 20895 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:236)
01-18 20:51:36.803 20895 20895 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:8063)
01-18 20:51:36.803 20895 20895 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
01-18 20:51:36.803 20895 20895 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:676)
01-18 20:51:36.803 20895 20895 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011)
01-18 20:51:36.803 20895 20895 E AndroidRuntime: Caused by: java.lang.IllegalArgumentException: Receiver not registered: de.cotech.hw.internal.transport.usb.UsbConnectionDispatcher$1@a1b05b6
01-18 20:51:36.803 20895 20895 E AndroidRuntime:        at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:1457)
01-18 20:51:36.803 20895 20895 E AndroidRuntime:        at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1652)
01-18 20:51:36.803 20895 20895 E AndroidRuntime:        at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:726)
01-18 20:51:36.803 20895 20895 E AndroidRuntime:        at de.cotech.hw.internal.transport.usb.UsbConnectionDispatcher.onInactive(UsbConnectionDispatcher.java:131)
01-18 20:51:36.803 20895 20895 E AndroidRuntime:        at de.cotech.hw.SecurityKeyManager$DispatcherActivityLifecycleCallbacks.ensureStateInactive(SecurityKeyManager.java:316)
01-18 20:51:36.803 20895 20895 E AndroidRuntime:        at de.cotech.hw.SecurityKeyManager$DispatcherActivityLifecycleCallbacks.refreshActiveState(SecurityKeyManager.java:290)
01-18 20:51:36.803 20895 20895 E AndroidRuntime:        at de.cotech.hw.SecurityKeyManager$DispatcherActivityLifecycleCallbacks.onActivityPaused(SecurityKeyManager.java:333)
01-18 20:51:36.803 20895 20895 E AndroidRuntime:        at android.app.Application.dispatchActivityPaused(Application.java:468)
01-18 20:51:36.803 20895 20895 E AndroidRuntime:        at android.app.Activity.dispatchActivityPaused(Activity.java:1481)
01-18 20:51:36.803 20895 20895 E AndroidRuntime:        at android.app.Activity.onPause(Activity.java:2439)
01-18 20:51:36.803 20895 20895 E AndroidRuntime:        at androidx.fragment.app.FragmentActivity.onPause(FragmentActivity.java:418)
01-18 20:51:36.803 20895 20895 E AndroidRuntime:        at org.connectbot.ConsoleActivity.onPause(ConsoleActivity.java:1037)
01-18 20:51:36.803 20895 20895 E AndroidRuntime:        at android.app.Activity.performPause(Activity.java:8343)
01-18 20:51:36.803 20895 20895 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1510)
01-18 20:51:36.803 20895 20895 E AndroidRuntime:        at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:4898)
01-18 20:51:36.803 20895 20895 E AndroidRuntime:        ... 12 more

```
